import joblib
import m2cgen as m2c
import os

def export_model_to_dart():
    model_path = "model/crop_model.pkl"
    dart_output_path = "../agrisense_app/lib/models/crop_model_data.dart"
    
    print(f"Loading model from {model_path}...")
    try:
        model = joblib.load(model_path)
    except FileNotFoundError:
        print("Model file not found. Please train it first.")
        return
        
    print("Exporting model to Dart using m2cgen...")
    code = m2c.export_to_dart(model)
    
    # We'll wrap this in a nice Dart class
    # The generated code will contain a function `double score(List<double> input)`
    # Wait, for Random Forest, m2cgen generates a single function that returns a List of probabilities if it's multiclass
    class_labels = list(model.classes_)
    
    dart_code = f"""
// AUTO-GENERATED BY M2CGEN
// Crop Recommendation Model
// Classes: {class_labels}

{code}

class CropModel {{
  static const List<String> classes = {class_labels};
  
  static List<double> predict(List<double> input) {{
    return score(input);
  }}
}}
"""
    
    print(f"Saving Dart code to {dart_output_path}...")
    with open(dart_output_path, "w") as f:
        f.write(dart_code)
    print("Done!")

if __name__ == "__main__":
    export_model_to_dart()
